name = "pansod-store"
pages_build_output_dir = "."
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "pansod-store-db"
database_id = "1407b63f-dcd1-4f50-ba88-40d4c7f8e4a3"
migrations_dir = "migrations"
